blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/detail', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

esqoffee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('products', include('shop.products.urls', namespace='products')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_process, name='order_create'),
    path('reservation/', views.book_reservation, name='book_reservation'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Quantity')
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    quantity.widget.attrs.update({'class': "quantity form-control input-number",})

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.products.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    else:
        cart.add(product=product, quantity=1, override_quantity=False)
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    template = 'cart/detail.html'

    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )

    context = {'cart': cart}
    return render(request, template, context)

templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Cart{% endblock %}
{% block content %}
    <section class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);"
             data-stellar-background-ratio="0.5">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center">
                    <div class="col-md-7 col-sm-12 text-center ftco-animate">
                        <h1 class="mb-3 mt-5 bread">Cart</h1>
                        <p class="breadcrumbs">
                            <span class="mr-2"><a href="{% url 'home' %}">Home</a></span>
                            <span>Cart</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section ftco-cart">
        <div class="container">
            <div class="row">
                <div class="col-md-12 ftco-animate">
                    <div class="cart-list">
                        <table class="table">
                            <thead class="thead-primary">
                            <tr class="text-center">
                                <th>&nbsp;</th>
                                <th>&nbsp;</th>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr class="text-center">
                                        <td class="product-remove">
                                            <form action="{% url "cart:cart_remove" product.id %}" method="post">
                                                {% csrf_token %}
                                                <button type="submit" class="quantity-right-plus btn"
                                                        data-type="remove"
                                                        data-field="">
                                                    <i class="icon-close"></i>
                                                </button>
                                            </form>
                                        </td>

                                        <td class="image-prod">
                                            <div class="img" style="background-image:url(
                                                    {% if product.image %}
                                                        {{ product.image.url }}
                                                    {% else %}
                                                        /static/images/delicious.png
                                                    {% endif %}
                                                    );"></div>
                                        </td>

                                        <td class="product-name">
                                            <h3>{{ product.name }}</h3>
                                            <p>{{ product.description|truncatechars:30 }}</p>
                                        </td>
                                        <td class="price">KES {{ item.price }}</td>
                                        <td class="quantity">
                                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <button type="submit" class="quantity-right-plus btn"
                                                        data-type="plus"
                                                        data-field="">
                                                    <i class="icon-refresh"></i>
                                                </button>
                                                {#                                                <input type="submit" value="Update">#}
                                                {% csrf_token %}
                                            </form>
                                            <div class="input-group mb-3">

                                                {#                                                <input type="text" name="quantity"#}
                                                {#                                                       class="quantity form-control input-number"#}
                                                {#                                                       value="1" min="1" max="100">#}
                                            </div>
                                        </td>
                                        <td class="total">KES {{ item.total_price }}</td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row justify-content-end">
                <div class="col col-lg-3 col-md-6 mt-5 cart-wrap ftco-animate">
                    <div class="cart-total mb-3">
                        <h3>Cart Totals</h3>
                        <p class="d-flex">
                            <span>Subtotal</span>
                            <span>KES {{ cart.get_total_price|floatformat:2 }}</span>
                        </p>
                        <p class="d-flex">
                            <span>Delivery</span>
                            <span>KES 0.00</span>
                        </p>
                        <p class="d-flex">
                            <span>Discount</span>
                            <span>KES {{ cart.get_discount|floatformat:2 }}</span>
                        </p>
                        <hr>
                        <p class="d-flex total-price">
                            <span>Total</span>
                            <span>KES {{ cart.get_total_price_after_discount|floatformat:2 }}</span>
                        </p>
                    </div>
                    {% if cart %}
                        <p class="text-center">
                            <a href="{% url "orders:order_create" %}" class="btn btn-primary py-3 px-4">
                                Proceed to Checkout
                            </a>
                        </p>
                    {% endif %}
                    <p class="text-center">
                        <a href="{% url "menu:product_list" %}" class="btn btn-primary py-3 px-4">
                            Continue Shopping
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </section>

{#    <section class="ftco-section">#}
{#        <div class="container">#}
{#            <div class="row justify-content-center mb-5 pb-3">#}
{#                <div class="col-md-7 heading-section ftco-animate text-center">#}
{#                    <span class="subheading">Discover</span>#}
{#                    <h2 class="mb-4">Related products</h2>#}
{#                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there#}
{#                        live the blind texts.</p>#}
{#                </div>#}
{#            </div>#}
{#            <div class="row">#}
{#                <div class="col-md-3">#}
{#                    <div class="menu-entry">#}
{#                        <a href="#" class="img" style="background-image: url(images/menu-1.jpg);"></a>#}
{#                        <div class="text text-center pt-4">#}
{#                            <h3><a href="#">Coffee Capuccino</a></h3>#}
{#                            <p>A small river named Duden flows by their place and supplies</p>#}
{#                            <p class="price"><span>$5.90</span></p>#}
{#                            <p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-md-3">#}
{#                    <div class="menu-entry">#}
{#                        <a href="#" class="img" style="background-image: url(images/menu-2.jpg);"></a>#}
{#                        <div class="text text-center pt-4">#}
{#                            <h3><a href="#">Coffee Capuccino</a></h3>#}
{#                            <p>A small river named Duden flows by their place and supplies</p>#}
{#                            <p class="price"><span>$5.90</span></p>#}
{#                            <p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-md-3">#}
{#                    <div class="menu-entry">#}
{#                        <a href="#" class="img" style="background-image: url(images/menu-3.jpg);"></a>#}
{#                        <div class="text text-center pt-4">#}
{#                            <h3><a href="#">Coffee Capuccino</a></h3>#}
{#                            <p>A small river named Duden flows by their place and supplies</p>#}
{#                            <p class="price"><span>$5.90</span></p>#}
{#                            <p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="col-md-3">#}
{#                    <div class="menu-entry">#}
{#                        <a href="#" class="img" style="background-image: url(images/menu-4.jpg);"></a>#}
{#                        <div class="text text-center pt-4">#}
{#                            <h3><a href="#">Coffee Capuccino</a></h3>#}
{#                            <p>A small river named Duden flows by their place and supplies</p>#}
{#                            <p class="price"><span>$5.90</span></p>#}
{#                            <p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{% endblock %}