blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/detail', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.contact_view, name='contact'),
]

esqoffee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('products', include('shop.products.urls', namespace='products')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

templates/includes/blog_sidebar.html
<div class="col-xl-4 sidebar ftco-animate">
    <div class="sidebar-box ftco-animate">
        <div class="categories">
            <h3>Categories</h3>
            {% for category in categories %}
                <li><a href="#">{{ category.name }} <span>({{ category.products.all.count }})</span></a></li>
            {% endfor %}
        </div>
    </div>

    <div class="sidebar-box ftco-animate">
        <h3>Recent Posts</h3>
        {% for post in recent_posts %}
            <div class="block-21 mb-4 d-flex">
                {% if post.poster %}
                    <a class="blog-img mr-4" style="background-image: url({{ post.poster.url }});"></a>
                {% else %}
                    <a class="blog-img mr-4"
                       style="background-image: url(/static/images/image_1.jpg);"></a>
                {% endif %}
                <div class="text">
                    <h3 class="heading">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h3>
                    <div class="meta">
                        <div><a href="{{ post.get_absolute_url }}"><span
                                class="icon-calendar"></span>{{ post.publish }}</a></div>
                        <div><a href="{{ post.get_absolute_url }}"><span
                                class="icon-person"></span> {{ post.author }}</a></div>
                        <div><a href="{{ post.get_absolute_url }}"><span
                                class="icon-chat"></span> {{ post.comments.count }}</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            There are no similar posts yet.
        {% endfor %}
    </div>

    <div class="sidebar-box ftco-animate">
        <h3>Tag Cloud</h3>
        <div class="tagcloud">
            {% for category in categories %}
                <a href="{% url 'blog:post_list_by_tag' category.slug %}" class="tag-cloud-link">{{ category.name }}</a>
            {% endfor %}
        </div>
    </div>
</div>

templates/includes/discover_menu.html
<section class="ftco-section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 pr-md-5">
                <div class="heading-section text-md-right ftco-animate">
                    <span class="subheading">Discover</span>
                    <h2 class="mb-4">Our Menu</h2>
                    <p class="mb-4">Far far away, behind the word mountains, far from the countries Vokalia and
                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the
                        coast of the Semantics, a large language ocean.</p>
                    <p><a href="#" class="btn btn-primary btn-outline-primary px-4 py-3">View Full Menu</a></p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <div class="menu-entry">
                            <a href="#" class="img" style="background-image: url(/static/images/menu-1.jpg);"></a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="menu-entry mt-lg-4">
                            <a href="#" class="img" style="background-image: url(/static/images/menu-2.jpg);"></a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="menu-entry">
                            <a href="#" class="img" style="background-image: url(/static/images/menu-3.jpg);"></a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="menu-entry mt-lg-4">
                            <a href="#" class="img" style="background-image: url(/static/images/menu-4.jpg);"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/includes/discover_story.html
{% load shop_tags %}

<section class="ftco-about d-md-flex">
    <div class="one-half img" style="background-image: url(/static/images/about.jpg);"></div>
    <div class="one-half ftco-animate">
        <div class="overlap">
            <div class="heading-section ftco-animate ">
                <span class="subheading">{{ story.subtitle }}</span>
                <h2 class="mb-4">{{ story.title }}</h2>
            </div>
            <div>
                <p>{{ story.story }}</p>
            </div>
        </div>
    </div>
</section>

templates/includes/discover_testimonials.html
<section class="ftco-section img" id="ftco-testimony" style="background-image: url(/static/images/bg_1.jpg);"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 heading-section text-center ftco-animate">
                <span class="subheading">Testimony</span>
                <h2 class="mb-4">Customers Says</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live
                    the blind texts.</p>
            </div>
        </div>
    </div>
    <div class="container-wrap">
        <div class="row d-flex no-gutters">
            {% for testimonial in testimonials  %}
            <div class="col-lg align-self-sm-end ftco-animate">
                <div class="testimony {% if forloop.counter|divisibleby:2 %}overlay{% endif %}">
                    <blockquote>
                        <p>&ldquo;{{ testimonial.testimony }}&rdquo;</p>
                    </blockquote>
                    <div class="author d-flex mt-4">
                        <div class="image mr-3 align-self-center">
                            <img src="/static/images/person_2.jpg" alt="">
                        </div>
                        <div class="name align-self-center">{{ testimonial.name }} <span
                                class="position">{{ testimonial.position }} </span></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

templates/includes/footer.html
{% load blog_tags %}
{% load shop_tags %}

<footer class="ftco-footer ftco-section img">
    <div class="overlay"></div>
    <div class="container">
        <div class="row mb-5">
            <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                {% show_footer_about %}
            </div>
            {% show_latest_posts %}
            <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-2 d-block">Cooked</a></li>
                        <li><a href="#" class="py-2 d-block">Deliver</a></li>
                        <li><a href="#" class="py-2 d-block">Quality Foods</a></li>
                        <li><a href="#" class="py-2 d-block">Mixed</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li>
                <span class="icon icon-map-marker"></span
                ><span class="text"
                            >Rift Valley Viewpoint, Kiambu, Nakuru-Nairobi Highway</span
                            >
                            </li>
                            <li>
                                <a href="#"
                                ><span class="icon icon-phone"></span
                                ><span class="text">+254723272788</span></a
                                >
                            </li>
                            <li>
                                <a href="#"
                                ><span class="icon icon-envelope"></span
                                ><span class="text">info@esqoffee.com</span></a
                                >
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    All rights reserved | &copy;
                    <i class="icon-heart" aria-hidden="true"></i> by
                    <a href="#" target="_blank">Robinson</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

templates/includes/footer_about.html
{% load shop_tags %}

<div class="ftco-footer-widget mb-4">
    <h2 class="ftco-heading-2">About Us</h2>
    <p>
        {{ story.story }}
    </p>
    <ul
            class="ftco-footer-social list-unstyled float-md-left float-lft mt-5"
    >
        <li class="ftco-animate">
            <a href="https://www.twitter.com/esqoffee" target="_blank"><span
                    class="icon-twitter"></span></a>
        </li>
        <li class="ftco-animate">
            <a href="https://www.facebook.com/esqoffee" target="_blank"><span
                    class="icon-facebook"></span></a>
        </li>
        <li class="ftco-animate">
            <a href="https://www.instagram.com/esqoffee" target="_blank"><span
                    class="icon-instagram"></span></a>
        </li>
    </ul>
</div>

templates/includes/navbar.html
<nav
        class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light"
        id="ftco-navbar"
>
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Esqoffee<small>Shop</small></a>
        <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#ftco-nav"
                aria-controls="ftco-nav"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'home' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item"><a href="{% url 'menu:product_list' %}" class="nav-link">Menu</a></li>
                <li class="nav-item">
                    <a href="{% url 'services' %}" class="nav-link">Services</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'blog:post_list' %}" class="nav-link">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'about' %}" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'contact:contact' %}" class="nav-link">Contact</a>
                </li>
                <li class="nav-item cart">
                    {% with total_items=cart|length %}
                        <a href="{% url 'cart:cart_detail' %}" class="nav-link">
                            <span class="icon icon-shopping_cart"></span>
                            <span class="bag d-flex justify-content-center align-items-center">
                                    <small>{{ total_items }}</small>
                                </span>
                        </a>
                    {% endwith %}
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->

templates/includes/our_services.html
<section class="ftco-section ftco-services">
    <div class="container">
        <div class="row">
            <div class="col-md-4 ftco-animate">
                <div class="media d-block text-center block-6 services">
                    <div class="icon d-flex justify-content-center align-items-center mb-5">
                        <span class="flaticon-choices"></span>
                    </div>
                    <div class="media-body">
                        <h3 class="heading">Easy to Order</h3>
                        <p>Even the all-powerful Pointing has no control about the blind texts it is an almost
                            unorthographic.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 ftco-animate">
                <div class="media d-block text-center block-6 services">
                    <div class="icon d-flex justify-content-center align-items-center mb-5">
                        <span class="flaticon-delivery-truck"></span>
                    </div>
                    <div class="media-body">
                        <h3 class="heading">Fastest Delivery</h3>
                        <p>Even the all-powerful Pointing has no control about the blind texts it is an almost
                            unorthographic.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-4 ftco-animate">
                <div class="media d-block text-center block-6 services">
                    <div class="icon d-flex justify-content-center align-items-center mb-5">
                        <span class="flaticon-coffee-bean"></span></div>
                    <div class="media-body">
                        <h3 class="heading">Quality Coffee</h3>
                        <p>Even the all-powerful Pointing has no control about the blind texts it is an almost
                            unorthographic.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/includes/our_stats.html
<section class="ftco-counter ftco-bg-dark img" id="section-counter" style="background-image: url(/static/images/bg_2.jpg);"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <div class="icon"><span class="flaticon-coffee-cup"></span></div>
                                <strong class="number" data-number="100">0</strong>
                                <span>Coffee Branches</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <div class="icon"><span class="flaticon-coffee-cup"></span></div>
                                <strong class="number" data-number="85">0</strong>
                                <span>Number of Awards</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <div class="icon"><span class="flaticon-coffee-cup"></span></div>
                                <strong class="number" data-number="10567">0</strong>
                                <span>Happy Customer</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-3 d-flex justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center">
                            <div class="text">
                                <div class="icon"><span class="flaticon-coffee-cup"></span></div>
                                <strong class="number" data-number="900">0</strong>
                                <span>Staff</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/includes/pagination.html
<div class="row mt-5">
    <div class="col text-center">
        <div class="block-27">
            <ul>
                {% if page.has_previous %}
                    <li><a href="?page={{ page.previous_page_number }}">&lt;</a></li>
                {% endif %}
                <li {% if page.number == 1 %}class="active"{% endif %}><span>{{ page.number }}</span></li>
                {% if page.has_next %}
                    <li><a href="?page={{ page.next_page_number }}">&gt;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

templates/includes/recent_posts.html
<div class="col-lg-4 col-md-6 mb-5 mb-md-5">
    <div class="ftco-footer-widget mb-4">
        <h2 class="ftco-heading-2">Recent Blog</h2>
        {% for post in latest_posts %}
            <div class="block-21 mb-4 d-flex">
                {% if post.poster %}
                    <a class="blog-img mr-4" style="background-image: url({{ post.poster.url }});"></a>
                {% else %}
                    <a class="blog-img mr-4" style="background-image: url(/static/images/delicious.png);"></a>
                {% endif %}

                <div class="text">
                    <h3 class="heading">
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.title }}
                        </a>
                    </h3>
                    <div class="meta">
                        <div>
                            <a href="{{ post.get_absolute_url }}">
                                <span class="icon-calendar"></span> {{ post.publish }}
                            </a>
                        </div>
                        <div>
                            <a href="{{ post.get_absolute_url }}">
                                <span class="icon-person"></span>{{ post.author }}
                            </a>
                        </div>
                        <div>
                            <a href="{{ post.get_absolute_url }}">
                                <span class="icon-chat"></span> {{ post.comments.count }}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>