blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/detail', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
]

esqoffee/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('products', include('shop.products.urls', namespace='products')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_process, name='order_create'),
    path('reservation/', views.book_reservation, name='book_reservation'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

templates/menu/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <section class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);"
             data-stellar-background-ratio="0.5">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center">
                    <div class="col-md-7 col-sm-12 text-center ftco-animate">
                        <h1 class="mb-3 mt-5 bread">Product Detail</h1>
                        <p class="breadcrumbs">
                            <span class="mr-2"><a href="{% url 'home' %}">Home</a></span>
                            <span>Product Detail</span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-5 ftco-animate">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" class="image-popup">
                            <img src="{{ product.image.url }}" class="img-fluid" alt="Colorlib Template">
                        </a>
                    {% else %}
                        <a href="/static/images/delicious.png" class="image-popup">
                            <img src="/static/images/delicious.png" class="img-fluid" alt="Colorlib Template">
                        </a>
                    {% endif %}
                </div>
                <div class="col-lg-6 product-details pl-md-5 ftco-animate">
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                        {% csrf_token %}
                        <h3>{{ product.name }}</h3>
                        <p class="price"><span>KES {{ product.price }}</span></p>
                        <p>{{ product.description }}</p>
{#                        <div class="row mt-4">#}
{#                            <div class="w-100"></div>#}
{#                            <div class="input-group col-md-6 d-flex mb-3">#}
{#                            <span class="input-group-btn mr-2">#}
{#                                <button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">#}
{#                                    <i class="icon-minus"></i>#}
{#                                </button>#}
{#                                </span>#}
{#                                <input type="text" id="quantity" name="quantity" class="form-control input-number"#}
{#                                       value="1"#}
{#                                       min="1" max="100">#}
{#                                <span class="input-group-btn ml-2">#}
{#                                <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">#}
{#                                     <i class="icon-plus"></i>#}
{#                                 </button>#}
{#                            </span>#}
{#                            </div>#}
{#                        </div>#}
                        <input class="btn btn-primary btn-outline-primary" type="submit" value="Add to cart">
                    </form>
                </div>
            </div>
        </div>
    </section>

    {% if recommended_products %}
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center mb-5 pb-3">
                    <div class="col-md-7 heading-section ftco-animate text-center">
                        <span class="subheading">Discover</span>
                        <h2 class="mb-4">Related products</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                            there
                            live the blind texts.</p>
                    </div>
                </div>

                <div class="row">
                    {% for p in recommended_products %}
                        <div class="col-md-3">
                            <div class="menu-entry">
                                <a href="#" class="img" style="background-image: url(/static/images/menu-1.jpg);"></a>
                                <div class="text text-center pt-4">
                                    <h3><a href="#">{{ p.name }}</a></h3>
                                    <p>{{ p.description }}</p>
                                    <p class="price"><span>KES {{ p.price }}</span></p>
                                    <p><a href="#" class="btn btn-primary btn-outline-primary">Add to Cart</a></p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}
{% endblock %}

templates/menu/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Menu{% endblock %}
{% block content %}
    <section class="home-slider owl-carousel">
        <div class="slider-item" style="background-image: url(/static/images/bg_3.jpg);"
             data-stellar-background-ratio="0.5">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text justify-content-center align-items-center">
                    <div class="col-md-7 col-sm-12 text-center ftco-animate">
                        <h1 class="mb-3 mt-5 bread">Our Menu</h1>
                        <p class="breadcrumbs">
                            <span class="mr-2"><a href="{% url 'home' %}">Home</a></span>
                            <span>Menu</span>
                        </p>
                    </div>

                </div>
            </div>
        </div>
    </section>
    <section class="ftco-intro">
        <div class="container-wrap">
            <div class="wrap d-md-flex align-items-xl-end">
                <div class="info">
                    <div class="row no-gutters">
                        <div class="col-md-4 d-flex ftco-animate">
                            <div class="icon"><span class="icon-phone"></span></div>
                            <div class="text">
                                <h3>+254723272788</h3>
                                <p>A small river named Duden flows by their place and supplies.</p>
                            </div>
                        </div>
                        <div class="col-md-4 d-flex ftco-animate">
                            <div class="icon"><span class="icon-my_location"></span></div>
                            <div class="text">
                                <h3>Nakuru-Nairobi Highway</h3>
                                <p> Rift Valley, View point,Kiambu, Kenya </p>
                            </div>
                        </div>
                        <div class="col-md-4 d-flex ftco-animate">
                            <div class="icon"><span class="icon-clock-o"></span></div>
                            <div class="text">
                                <h3>Open Monday-Sunday</h3>
                                <p>8:00am - 9:00pm</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="book p-4">
                    <h3>Book a Table</h3>
                    <form method="post" action="{% url 'orders:book_reservation' %}" class="appointment-form">
                        {% csrf_token %}
                        <div class="d-md-flex">
                            <div class="form-group">
                                {{ reservation_form.first_name }}
                            </div>
                            <div class="form-group ml-md-4">
                                {{ reservation_form.last_name }}
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-md-calendar"></span></div>
                                     {{ reservation_form.date }}
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                <div class="input-wrap">
                                    <div class="icon"><span class="ion-ios-clock"></span></div>
                                     {{ reservation_form.time }}
                                </div>
                            </div>
                            <div class="form-group ml-md-4">
                                 {{ reservation_form.phone }}
                            </div>
                        </div>
                        <div class="d-md-flex">
                            <div class="form-group">
                                {{ reservation_form.message }}
                            </div>
                            <div class="form-group ml-md-4">
                                <input type="submit" value="Appointment" class="btn btn-white py-3 px-4">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                {% for category in categories %}
                    <div class="col-md-6 mb-5 pb-3">
                        <h3 class="mb-5 heading-pricing ftco-animate">{{ category.name }}</h3>

                        {% for product in category.products.all %}
                            <div class="pricing-entry d-flex ftco-animate">
                                {% if product.image %}
                                    <div class="img" style="background-image: url({{ product.image.url }});"></div>
                                {% else %}
                                    <div class="img" style="background-image: url(/static/images/delicious.png);"></div>
                                {% endif %}
                                <div class="desc pl-3">
                                    <div class="d-flex text align-items-center">
                                        <h3><span>{{ product.name }}</span></h3>
                                        <span class="price">KES {{ product.price }}</span>
                                    </div>
                                    <div class="d-block">
                                        <p>{{ product.description }}</p>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            There are products yet!
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <section class="ftco-menu mb-5 pb-5">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-7 heading-section text-center ftco-animate">
                    <span class="subheading">Discover</span>
                    <h2 class="mb-4">Our Products</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                </div>
            </div>

            <div class="row d-md-flex">
                <div class="col-lg-12 ftco-animate p-md-5">
                    <div class="row">
                        <div class="col-md-12 nav-link-wrap mb-5">
                            <div class="nav ftco-animate nav-pills justify-content-center" id="v-pills-tab"
                                 role="tablist" aria-orientation="vertical">
                                {% for category in categories %}
                                    <a id="v-pills-{{ forloop.counter }}-tab"
                                       class="nav-link"
                                       data-toggle="pill"
                                       href="#v-pills-{{ forloop.counter }}"
                                       role="tab" aria-controls="v-pills-{{ forloop.counter }}" aria-selected="true">
                                        {{ category.name }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="col-md-12 d-flex align-items-center">
                            <div class="tab-content ftco-animate" id="v-pills-tabContent">
                                {% for category in categories %}
                                    <div id="v-pills-{{ forloop.counter }}" role="tabpanel"
                                         class="tab-pane fade {% if forloop.counter == 1 %} active show {% endif %}"
                                         aria-labelledby="v-pills-{{ forloop.counter }}-tab">
                                        <div class="row">
                                            {% for product in category.products.all %}
                                                <div class="col-md-4 text-center">
                                                    <div class="menu-wrap">
                                                        {% if product.image %}
                                                            <a href="{{ product.get_absolute_url }}"
                                                               class="menu-img img mb-4"
                                                               style="background-image: url({{ product.image.url }});"></a>
                                                        {% else %}
                                                            <a href="{{ product.get_absolute_url }}"
                                                               class="menu-img img mb-4"
                                                               style="background-image: url(/static/images/delicious.png);"></a>
                                                        {% endif %}
                                                        <div class="text">
                                                            <h3>
                                                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                                            </h3>
                                                            <p>{{ product.description }}</p>
                                                            <p class="price"><span>KES {{ product.price }}</span></p>
                                                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                                                {% csrf_token %}
                                                                <input class="btn btn-primary btn-outline-primary" type="submit" value="Add to cart">
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            {% empty %}
                                                <div class="text-center">No products yet!</div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}